# Generated by Django 4.1.3 on 2022-11-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_details", "0003_tag_order_tags"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="tags",),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(to="account_details.tag"),
        ),
    ]
