# Generated by Django 4.1.3 on 2022-11-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_details", "0004_remove_order_tags_product_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="note",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
